config/routes.rb
Rails.application.routes.draw do

    devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"}

    root "application#home"

    resources :reports
    resources :responses
    resources :users
    resources :categories
    resources :listings

  end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :listings
end

app/models/listing.rb
class Listing < ActiveRecord::Base

  belongs_to :category, optional: true
  belongs_to :user, optional: true
  has_many :responses
  has_many :reports

  validates_presence_of :title, :company, :location, :employment_type, :description, :requirements, :retribution, :category_title


  def category_title=(title)
     self.category = Category.find_or_create_by(title: title)
  end

   def category_title
      self.category ? self.category.title : nil
    end

end

app/models/report.rb
class Report < ActiveRecord::Base

  belongs_to :listing, optional: true
  belongs_to :user, optional: true
end

app/models/response.rb
class Response < ActiveRecord::Base

  belongs_to :user, optional: true
  belongs_to :listing
end

app/models/user.rb
class User < ActiveRecord::Base
  extend Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable, :omniauthable

  has_many :listings
  has_many :responses, through: :listings
  has_many :reports, through: :listings

  validates :username, :uniqueness => {:case_sensitive => false}
  validates :username, presence: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.serialize_into_session(record)
    [record.to_key.map(&:to_s), record.authenticatable_salt]
  end

  def self.serialize_into_cookie(record)
    [record.to_key.map(&:to_s), record.rememberable_value]
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def home
    @listings = Listing.all
    @categories = Category.all
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end




end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
		@listings = @category.listings
  end


end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @listings = Listing.all
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    if @listing.save
      redirect_to listing_path(@listing)
    else
      redirect_to new_listing_path
    end
  end

  def show
    @listing = Listing.find(params[:id])
  end



private

 def listing_params
   params.require(:listing).permit(:title, :company, :location, :description, :employment_type, :requirements, :retribution, :category_title)
 end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # Set a session value
  session[:current_user_id] = user.id

  # Access a session value
  some_other_variable_value = session[:other_variable_key]

  # Reset a session key
  session[:key_to_be_reset] = nil

  # Reset the entire session
  reset_session
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.html.erb
<% if user_signed_in? %>
<h3>Welcome <%=current_user.username%>!</h3>
<%end%>


<h1>Job offers</h1>

<h2>Search by category:</h2>

<% @categories.each do |category| %>
  <%= link_to category.title, category_path(category) %>
<%end%>

<h2>Or browse through the latest <%= link_to 'offers', listings_path%></h2>

<div>
  Are you an Employer? Post a job <%= link_to 'here', new_listing_path%></li>
</div>

app/views/categories/show.html.erb
<h2>See all the jobs available in this category:</h2>

<%@listings.each do |listing|%>
<li><%=link_to listing.title, listing_path(listing)%></li>
<%end%>

app/views/layouts/_navbar.html.erb
<%=link_to('Home', '/') %>
<% if user_signed_in? %>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SteveJobs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
    <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
    <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/listings/index.html.erb
<h1>Job offers list</h1>

<%@listings.each do |listing|%>
<li><%=link_to listing.title, listing_path(listing)%></li>
<%end%>

app/views/listings/new.html.erb
<div> Choose a category from the list below: </div>


<%= form_for @listing do |f| %>
<%= f.collection_select :category_title, Category.all, :title, :title %><br><br>

<%= f.label :title %>
<%= f.text_field :title %><br>
<%= f.label :company, "Company name (if Private please state your name):" %>
<%= f.text_field :company %><br>
<%= f.label :location, "Where:"%>
<%= f.text_field :location %><br>
<%= f.label :employment_type %>
<%= f.text_field :employment_type %><br><br>
<%= f.label :description %><br>
<%= f.text_area :description %><br>
<%= f.label :requirements %><br>
<%= f.text_area :requirements %><br><br>
<%= f.label :retribution, "Retribution (per month): $"%>
<%= f.number_field :retribution %><br><br>


<%= f.submit %>
  <% end %>

app/views/listings/show.html.erb
<h2><%=@listing.title%></h2>
<strong>Company: </strong> <%=@listing.company%><br>
<strong>Location: </strong> <%=@listing.location%><br>
<strong>Employment type: </strong> <%=@listing.employment_type%><br>
<strong>Description</strong><br>
<%=@listing.description%><br>
<strong>Requirements</strong><br>
<%=@listing.requirements%><br>
<strong>Retribution per month: </strong>$<%=@listing.retribution%>